# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Pythias
email: engineering@pythias.tech
author: Andrew Kamau
description: > # "Write an awesome description for your new site here. 
  pythias.io
copyright: 'Copyright &copy; 2016 Pythias. All Rights Reserved.'
credits: ''

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pythias.io/"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/pythias_io
  - title: github
    url: https://bitbucket.org/pythias_io
  - title: email
    url: mailto:info@pythias.io
